version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./model_connection_example:/app/model_connection_example  # If your code needs it
      - ./model_connection_example/input_data:/app/model_connection_example/input_data
      - ./model_connection_example/data_output:/app/model_connection_example/data_output
      - ./model_connection_example/docs:/app/model_connection_example/docs
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
